language: python
python:
  - "2.7"
notifications:
  email: false
# command to install dependencies
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install: 
  - conda env create --yes python=$TRAVIS_PYTHON_VERSION -f conda.yml
  - source activate crt
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: 
  -  find . -path ./scripts -prune -o -name \*.py -exec pep8 --ignore=E402,E501,E265,E731,E712 {} +
