# amino acid to exclude from the plot
# this will speed up a lot the data generation
# If you exclude an amino acid, there won't be a reassignation to that aa
EXCLUDE_AA: "ACDEFHIKLMNPQTVWY"

# If you exclude a aa, there won't be a reassignation from that aa
EXCLUDE_AA_FROM: "ACDEFHIKLMNPQTVWY"

# Threshold require to determine if an aa is majoritary in a column
AA_MAJORITY_THRESH: 0.5

# Mode to compute suspected species
# possible values : count, wilcoxon, mannwhitney, kmean, ttest
# kmean does not work well, use wilcoxon
MODE: 'wilcoxon'

# Distance matrice:
MATRIX: 'identity'

# Codon to amino acid likelihood. Use consensus or complete
# alignement for Telford score
USE_CONSENSUS_FOR_LIKELIHOOD: False

# Show codon in non conserved position for its amino acid
SHOW_MIXTE_CODONS: False

# Show Filtered codon data
SHOW_GLOBAL_CODON_DATA: False

# Add the total count in each pie chart in the
# codon detail figure
ADD_NUMBER_PIE: False

# alpha : rejection of the null hypothesis
CONF: 0.05

# Selection start codon range
STARTDIST: 20
