{% set version = "1.1.3" %}

package:
  name: coretracker
  version: "{{ version }}"

source:
  fn: CoreTracker-1.1.3.tar.gz
  url: https://pypi.python.org/packages/5b/b3/00581ccc4bd0a1aaf428be1f4badde61f7ea4c09d24c9a1f2e21e9e60a09/CoreTracker-1.1.3.tar.gz
  md5: 1535aadc401d7a99e89527656977226a

build:
  binary_relocation: True
  preserve_egg_dir: True
  detect_binary_files_with_prefix: True
  number: 6

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.1
    - scipy >=0.16.1
    - matplotlib
    - biopython >=1.65
    - scikit-learn ==0.17
    - weasyprint
    - pyyaml
    - pandas
    - ete3
    - libgfortran
    - muscle
    - hmmer
    - mafft

  run:
    - python
    - numpy >=1.8.1
    - scipy >=0.16.1
    - matplotlib
    - biopython >=1.65
    - scikit-learn ==0.17
    - weasyprint
    - pyyaml
    - pandas
    - ete3   
    - muscle
    - hmmer
    - mafft


test:
  # Python imports
  imports:
    - coretracker.FisherExact
    - coretracker.classifier
    - coretracker.coreutils
    - coretracker.settings
 
  commands:
    - coretracker -h
    - coreconvert -h
    - corefus -h
    - codonclust -h
    - coretrans -h


about:
  home: https://github.com/UdeM-LBIT/CoreTracker
  license: GNU General Public License (GPL)
  summary: 'CoreTracker, A codon reassignment tracker'
  license_family: LGPL
